# Generated by Django 2.1.3 on 2019-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_Type',
            field=models.BooleanField(),
        ),
    ]
