# Generated by Django 2.1.3 on 2019-04-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentsdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_id', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
