# Generated by Django 2.1.3 on 2019-04-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_coursesdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsdocument',
            name='Student_id',
        ),
    ]
