# Generated by Django 2.1.3 on 2019-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_coursesdocument_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
